# Generated by Django 5.2.17 on 2026-08-21 15:36

import apps.orders.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'carrito',
                'verbose_name_plural': 'carritos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='cantidad')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.carrito', verbose_name='carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='catalog.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'item del carrito',
                'verbose_name_plural': 'items del carrito',
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('numero', models.CharField(default=apps.orders.models.generar_numero_pedido, editable=False, max_length=24, unique=True, verbose_name='numero')),
                ('direccion_texto', models.CharField(max_length=300, verbose_name='direccion de entrega')),
                ('estado', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('PAGADO', 'Pagado'), ('EN_PREPARACION', 'En preparacion'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_PAGO', max_length=20, verbose_name='estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='subtotal')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='descuento')),
                ('costo_domicilio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='costo del domicilio')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='total')),
                ('notas', models.CharField(blank=True, max_length=300, verbose_name='notas')),
                ('direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='accounts.direccion', verbose_name='direccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre_producto', models.CharField(max_length=120, verbose_name='nombre del producto')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio unitario')),
                ('unidad_medida', models.CharField(max_length=10, verbose_name='unidad de medida')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='subtotal')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_pedido', to='catalog.producto', verbose_name='producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'item del pedido',
                'verbose_name_plural': 'items del pedido',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='carrito',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('usuario',), name='un_carrito_activo_por_usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together={('carrito', 'producto')},
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario', '-creado_en'], name='orders_pedi_usuario_8ae268_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado', '-creado_en'], name='orders_pedi_estado_b3f9c7_idx'),
        ),
    ]
