# Generated by Django 5.2.17 on 2026-09-05 20:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripcion')),
                ('presentacion', models.CharField(max_length=60, verbose_name='presentacion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio')),
                ('foto_url', models.URLField(blank=True, max_length=500, verbose_name='foto')),
                ('disponible', models.BooleanField(default=True, verbose_name='disponible')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalog.categoria', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-disponible', 'nombre'],
                'indexes': [models.Index(fields=['disponible'], name='catalog_prod_dispon_idx')],
            },
        ),
    ]
