# Generated by Django 5.2.17 on 2026-08-21 15:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripcion')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripcion')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en COP por unidad de medida.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='precio')),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramo'), ('UNIDAD', 'Unidad')], default='KG', max_length=10, verbose_name='unidad de medida')),
                ('stock', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='En kilos o unidades, segun la unidad de medida.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='stock')),
                ('disponible', models.BooleanField(default=True, verbose_name='disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalog.categoria', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripcion')),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO_FIJO', 'Monto fijo')], max_length=12, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Porcentaje (1-100) o monto en COP, segun el tipo.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('inicia_en', models.DateTimeField(verbose_name='inicia en')),
                ('termina_en', models.DateTimeField(verbose_name='termina en')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('productos', models.ManyToManyField(blank=True, related_name='promociones', to='catalog.producto', verbose_name='productos')),
            ],
            options={
                'verbose_name': 'promocion',
                'verbose_name_plural': 'promociones',
                'ordering': ['-inicia_en'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'disponible'], name='catalog_pro_categor_232a22_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['disponible', 'nombre'], name='catalog_pro_disponi_b89c7a_idx'),
        ),
    ]
