# Generated by Django 5.2.17 on 2026-09-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='archivado',
            field=models.BooleanField(default=False, verbose_name='archivado'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['archivado'], name='catalog_prod_archiv_idx'),
        ),
    ]
