# Generated by Django 5.2.17 on 2026-10-08 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_producto_archivado_producto_catalog_prod_archiv_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('porcentaje', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='porcentaje de descuento')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de fin')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('productos', models.ManyToManyField(related_name='promociones', to='catalog.producto', verbose_name='productos')),
            ],
            options={
                'verbose_name': 'promocion',
                'verbose_name_plural': 'promociones',
                'ordering': ['-fecha_inicio', 'nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='promo_fechas_en_orden'), models.CheckConstraint(condition=models.Q(('porcentaje__gte', 1), ('porcentaje__lte', 99)), name='promo_porcentaje_valido')],
            },
        ),
    ]
