# Generated by Django 5.2.18 on 2026-10-09 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_producto_archivado_producto_catalog_prod_archiv_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electronico')),
                ('telefono', models.CharField(max_length=20, verbose_name='telefono')),
                ('direccion', models.CharField(max_length=200, verbose_name='direccion')),
                ('municipio', models.CharField(max_length=80, verbose_name='municipio')),
                ('barrio', models.CharField(max_length=120, verbose_name='barrio')),
                ('notas', models.CharField(blank=True, max_length=300, verbose_name='notas para la entrega')),
                ('estado', models.CharField(choices=[('por_confirmar', 'Por confirmar (transferencia)'), ('por_cobrar', 'Por cobrar (contraentrega)'), ('pagado', 'Pagado')], max_length=13, verbose_name='estado')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia'), ('contraentrega_qr', 'Contraentrega con QR'), ('contraentrega_datafono', 'Contraentrega con datafono')], max_length=22, verbose_name='metodo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado')], default='pendiente', max_length=10, verbose_name='estado')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('referencia', models.CharField(blank=True, max_length=60, verbose_name='referencia de la transferencia')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='pedidos.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='catalog.producto', verbose_name='producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'item del pedido',
                'verbose_name_plural': 'items del pedido',
                'ordering': ['id'],
            },
        ),
    ]
