# Generated by Django 5.2.17 on 2026-08-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WompiEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('checksum', models.CharField(max_length=128, unique=True, verbose_name='checksum')),
                ('evento', models.CharField(max_length=64, verbose_name='evento')),
                ('transaccion_id', models.CharField(blank=True, max_length=64, verbose_name='id de transaccion')),
            ],
            options={
                'verbose_name': 'evento de Wompi',
                'verbose_name_plural': 'eventos de Wompi',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('referencia', models.CharField(help_text='Referencia unica enviada a Wompi.', max_length=64, unique=True, verbose_name='referencia')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=12, verbose_name='estado')),
                ('monto_en_centavos', models.PositiveBigIntegerField(verbose_name='monto en centavos')),
                ('moneda', models.CharField(default='COP', max_length=3, verbose_name='moneda')),
                ('wompi_transaction_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='id de transaccion en Wompi')),
                ('metodo_pago', models.CharField(blank=True, help_text='Lo que reporte Wompi. En el MVP siempre CARD.', max_length=32, verbose_name='metodo de pago')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='respuesta de Wompi')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='orders.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
