# Generated by Django 5.2.18 on 2026-10-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('municipio', models.CharField(max_length=80, verbose_name='municipio')),
                ('barrio', models.CharField(max_length=120, verbose_name='barrio')),
                ('activa', models.BooleanField(default=True, help_text='Desmarcala para dejar de cubrir el barrio sin borrarlo.', verbose_name='activa')),
                ('clave', models.CharField(editable=False, max_length=210, unique=True, verbose_name='clave')),
            ],
            options={
                'verbose_name': 'zona de cobertura',
                'verbose_name_plural': 'zonas de cobertura',
                'ordering': ['municipio', 'barrio'],
            },
        ),
    ]
